server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tomatespodresdb?useSSL=false
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      database-platform: org.hibernate.dialect.MySQL8Dialect


  mail:
    host: smtp.gmail.com
    port: 587
    username: testeapi30@gmail.com
    password: goxqjpnjbxfzhein
    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000



swagger:
